/**
 * Référentiel automobile de départ (Automotive Knowledge Engine) : marques, types de véhicules, familles de pièces.
 *
 * NATURE DES DONNÉES — à lire avant d'utiliser :
 *  - Les marques ci-dessous (nom, pays d'origine, catégories de véhicules, état) viennent de la connaissance générale de
 *    l'IA qui a rédigé ce fichier. Elles n'ont PAS été vérifiées contre une base officielle : source
 *    `connaissance_generale_ia`, fiabilité non renseignée, statut « propose » (un fait vu une seule fois reste une
 *    proposition). Une seconde source indépendante (NHTSA, constructeur, base sous licence) les confirme par accumulation.
 *  - La liste n'est PAS exhaustive : elle couvre les marques notables du monde entier, anciennes et actuelles. Les marques
 *    récentes ou confidentielles arrivent par les synchronisations de sources (nhtsa.ts) et par la veille.
 *  - Le pays est celui d'origine de la marque, pas celui du propriétaire actuel. Aucune année, aucun groupe propriétaire,
 *    aucun modèle n'est inscrit ici : ils changent, et rien ici ne permet de les garantir.
 */

export const CATEGORIES_VEHICULE: Record<string, string> = {
  A: "Voiture particulière",
  L: "Luxe / prestige",
  S: "Sportive / supercar",
  E: "Électrique (marque ou gamme)",
  U: "Utilitaire léger",
  C: "Camion / poids lourd",
  B: "Bus / autocar",
  M: "Moto",
  Q: "Scooter / cyclomoteur",
  V: "Quad / tout-terrain / side-by-side",
  T: "Tracteur / matériel agricole",
  X: "Engin de chantier (BTP)",
  R: "Camping-car / caravane",
  Y: "Voiturette (sans permis / quadricycle)",
};

export interface MarqueReferentiel {
  nom: string;
  /** Code ISO 3166-1 alpha-2 du pays d'origine (MC = Monaco). */
  pays: string;
  /** Lettres de CATEGORIES_VEHICULE. */
  categories: string;
  /** "active" | "disparue" | "relancee" — état connu de l'IA rédactrice, à vérifier. */
  etat: "active" | "disparue" | "relancee";
}

const M = (nom: string, pays: string, categories: string, e = ""): MarqueReferentiel => ({
  nom,
  pays,
  categories,
  etat: e === "D" ? "disparue" : e === "R" ? "relancee" : "active",
});

export const MARQUES_REFERENTIEL: MarqueReferentiel[] = [
  M("Renault", "FR", "AU"),
  M("Dacia", "RO", "A"),
  M("Alpine", "FR", "S"),
  M("Peugeot", "FR", "AU"),
  M("Citroën", "FR", "AU"),
  M("DS Automobiles", "FR", "AL"),
  M("Bugatti", "FR", "LS"),
  M("Venturi", "MC", "SE"),
  M("Ligier", "FR", "Y"),
  M("Aixam", "FR", "Y"),
  M("Microcar", "FR", "Y"),
  M("Chatenet", "FR", "Y"),
  M("Renault Trucks", "FR", "C"),
  M("Iveco Bus", "FR", "B"),
  M("Heuliez Bus", "FR", "B"),
  M("Matra", "FR", "S", "D"),
  M("Simca", "FR", "A", "D"),
  M("Talbot", "FR", "A", "D"),
  M("Panhard", "FR", "A", "D"),
  M("Delahaye", "FR", "L", "D"),
  M("Facel Vega", "FR", "L", "D"),
  M("Hotchkiss", "FR", "A", "D"),
  M("Sherco", "FR", "M"),
  M("Peugeot Motocycles", "FR", "Q"),
  M("MBK", "FR", "Q"),
  M("Mash", "FR", "M"),
  M("Volkswagen", "DE", "AU"),
  M("Audi", "DE", "AL"),
  M("Porsche", "DE", "LS"),
  M("BMW", "DE", "AL"),
  M("BMW Motorrad", "DE", "M"),
  M("Mercedes-Benz", "DE", "ALU"),
  M("Mercedes-AMG", "DE", "LS"),
  M("Mercedes-Maybach", "DE", "L"),
  M("Maybach", "DE", "L", "D"),
  M("Smart", "DE", "AE"),
  M("Opel", "DE", "AU"),
  M("Alpina", "DE", "L"),
  M("Brabus", "DE", "L"),
  M("Ruf", "DE", "S"),
  M("Wiesmann", "DE", "S", "R"),
  M("Borgward", "DE", "A", "R"),
  M("Trabant", "DE", "A", "D"),
  M("Wartburg", "DE", "A", "D"),
  M("NSU", "DE", "A", "D"),
  M("DKW", "DE", "AM", "D"),
  M("Horch", "DE", "L", "D"),
  M("MAN", "DE", "CB"),
  M("Setra", "DE", "B"),
  M("Neoplan", "DE", "B"),
  M("Kässbohrer", "DE", "B"),
  M("Magirus", "DE", "C"),
  M("Hanomag", "DE", "CT", "D"),
  M("Fendt", "DE", "T"),
  M("Claas", "DE", "T"),
  M("Deutz-Fahr", "DE", "T"),
  M("Zündapp", "DE", "MQ", "D"),
  M("MZ", "DE", "M"),
  M("Horex", "DE", "M", "R"),
  M("Hercules", "DE", "MQ", "D"),
  M("Kreidler", "DE", "Q"),
  M("Simson", "DE", "Q", "D"),
  M("Maico", "DE", "M", "D"),
  M("Liebherr", "DE", "X"),
  M("Fiat", "IT", "AU"),
  M("Fiat Professional", "IT", "U"),
  M("Abarth", "IT", "S"),
  M("Alfa Romeo", "IT", "AS"),
  M("Lancia", "IT", "A"),
  M("Maserati", "IT", "LS"),
  M("Ferrari", "IT", "LS"),
  M("Lamborghini", "IT", "LS"),
  M("Pagani", "IT", "S"),
  M("De Tomaso", "IT", "S", "R"),
  M("Iveco", "IT", "CU"),
  M("Piaggio", "IT", "MQU"),
  M("Vespa", "IT", "Q"),
  M("Aprilia", "IT", "M"),
  M("Moto Guzzi", "IT", "M"),
  M("Ducati", "IT", "M"),
  M("Benelli", "IT", "M"),
  M("MV Agusta", "IT", "M"),
  M("Gilera", "IT", "MQ"),
  M("Laverda", "IT", "M", "D"),
  M("Moto Morini", "IT", "M"),
  M("Fantic", "IT", "M"),
  M("Beta", "IT", "M"),
  M("Bimota", "IT", "M"),
  M("Cagiva", "IT", "M"),
  M("Italjet", "IT", "Q"),
  M("Malaguti", "IT", "Q"),
  M("Lambretta", "IT", "Q", "R"),
  M("Innocenti", "IT", "A", "D"),
  M("Autobianchi", "IT", "A", "D"),
  M("Tazzari", "IT", "E"),
  M("Landini", "IT", "T"),
  M("Same", "IT", "T"),
  M("Lamborghini Trattori", "IT", "T"),
  M("Carraro", "IT", "T"),
  M("Lotus", "GB", "S"),
  M("Rolls-Royce", "GB", "L"),
  M("Bentley", "GB", "L"),
  M("Aston Martin", "GB", "LS"),
  M("Jaguar", "GB", "AL"),
  M("Land Rover", "GB", "A"),
  M("Range Rover", "GB", "AL"),
  M("Mini", "GB", "A"),
  M("MG", "GB", "AE"),
  M("McLaren", "GB", "S"),
  M("Morgan", "GB", "S"),
  M("Caterham", "GB", "S"),
  M("TVR", "GB", "S"),
  M("Ariel", "GB", "S"),
  M("Noble", "GB", "S"),
  M("Vauxhall", "GB", "AU"),
  M("Austin", "GB", "A", "D"),
  M("Morris", "GB", "A", "D"),
  M("Rover", "GB", "A", "D"),
  M("Triumph", "GB", "AS", "D"),
  M("Triumph Motorcycles", "GB", "M"),
  M("Norton", "GB", "M"),
  M("BSA", "GB", "M", "R"),
  M("Royal Enfield", "GB", "M"),
  M("Vincent HRD", "GB", "M", "D"),
  M("Reliant", "GB", "A", "D"),
  M("Jensen", "GB", "S", "D"),
  M("Westfield", "GB", "S"),
  M("Ginetta", "GB", "S"),
  M("Radical", "GB", "S"),
  M("Lister", "GB", "S"),
  M("Bristol", "GB", "L", "D"),
  M("AC Cars", "GB", "S"),
  M("Alexander Dennis", "GB", "B"),
  M("Optare", "GB", "B"),
  M("Leyland", "GB", "CB", "D"),
  M("ERF", "GB", "C", "D"),
  M("Foden", "GB", "C", "D"),
  M("JCB", "GB", "X"),
  M("Massey Ferguson", "GB", "T"),
  M("LDV", "GB", "U", "D"),
  M("Volvo", "SE", "AU"),
  M("Volvo Trucks", "SE", "C"),
  M("Polestar", "SE", "AE"),
  M("Saab", "SE", "A", "D"),
  M("Koenigsegg", "SE", "S"),
  M("Scania", "SE", "CB"),
  M("Husqvarna", "SE", "M"),
  M("DAF", "NL", "C"),
  M("Spyker", "NL", "S"),
  M("Donkervoort", "NL", "S"),
  M("VDL", "NL", "B"),
  M("Škoda", "CZ", "A"),
  M("Tatra", "CZ", "C"),
  M("Praga", "CZ", "S"),
  M("Jawa", "CZ", "M"),
  M("ČZ", "CZ", "M"),
  M("Karosa", "CZ", "B", "D"),
  M("SEAT", "ES", "A"),
  M("Cupra", "ES", "AS"),
  M("Hispano-Suiza", "ES", "L", "D"),
  M("Pegaso", "ES", "C", "D"),
  M("Santana", "ES", "A", "D"),
  M("Derbi", "ES", "MQ"),
  M("GasGas", "ES", "M"),
  M("Bultaco", "ES", "M", "R"),
  M("Montesa", "ES", "M"),
  M("Ossa", "ES", "M"),
  M("Rieju", "ES", "M"),
  M("Torrot", "ES", "ME"),
  M("Silence", "ES", "E"),
  M("Irizar", "ES", "B"),
  M("KTM", "AT", "M"),
  M("Steyr", "AT", "CT"),
  M("Puch", "AT", "MQ", "D"),
  M("Brixton", "AT", "M"),
  M("Magna Steyr", "AT", "A"),
  M("Rimac", "HR", "SE"),
  M("Zenvo", "DK", "S"),
  M("Sbarro", "CH", "S"),
  M("Rinspeed", "CH", "S"),
  M("Monteverdi", "CH", "L", "D"),
  M("Lada", "RU", "A"),
  M("GAZ", "RU", "CU"),
  M("UAZ", "RU", "A"),
  M("KAMAZ", "RU", "C"),
  M("ZIL", "RU", "C", "D"),
  M("Moskvich", "RU", "A", "R"),
  M("Volga", "RU", "A", "D"),
  M("Aurus", "RU", "L"),
  M("Ural", "RU", "M"),
  M("Izh", "RU", "M", "D"),
  M("ZAZ", "UA", "A", "D"),
  M("Bogdan", "UA", "AB"),
  M("LAZ", "UA", "B"),
  M("KrAZ", "UA", "C"),
  M("Dnepr", "UA", "M", "D"),
  M("MAZ", "BY", "CB"),
  M("BelAZ", "BY", "X"),
  M("FSO", "PL", "A", "D"),
  M("Solaris", "PL", "B"),
  M("Autosan", "PL", "B"),
  M("Ursus", "PL", "T"),
  M("Jelcz", "PL", "C"),
  M("Ikarus", "HU", "B", "D"),
  M("Rába", "HU", "CT"),
  M("Aro", "RO", "A", "D"),
  M("Togg", "TR", "AE"),
  M("Tofaş", "TR", "A"),
  M("Karsan", "TR", "B"),
  M("Otokar", "TR", "B"),
  M("BMC", "TR", "C"),
  M("Temsa", "TR", "B"),
  M("Anadol", "TR", "A", "D"),
  M("Toyota", "JP", "AUC"),
  M("Lexus", "JP", "AL"),
  M("Daihatsu", "JP", "A"),
  M("Honda", "JP", "AM"),
  M("Acura", "JP", "AL"),
  M("Nissan", "JP", "AU"),
  M("Infiniti", "JP", "AL"),
  M("Datsun", "JP", "A"),
  M("Mazda", "JP", "A"),
  M("Subaru", "JP", "A"),
  M("Suzuki", "JP", "AMQ"),
  M("Mitsubishi", "JP", "AU"),
  M("Isuzu", "JP", "UC"),
  M("Hino", "JP", "C"),
  M("Mitsubishi Fuso", "JP", "C"),
  M("UD Trucks", "JP", "C"),
  M("Yamaha", "JP", "MQV"),
  M("Kawasaki", "JP", "MV"),
  M("Mitsuoka", "JP", "A"),
  M("Scion", "JP", "A", "D"),
  M("Kubota", "JP", "TX"),
  M("Komatsu", "JP", "X"),
  M("Hitachi Construction Machinery", "JP", "X"),
  M("Hyundai", "KR", "AUC"),
  M("Kia", "KR", "AU"),
  M("Genesis", "KR", "AL"),
  M("SsangYong", "KR", "A"),
  M("KG Mobility", "KR", "A"),
  M("Daewoo", "KR", "A", "D"),
  M("Renault Korea", "KR", "A"),
  M("Hyundai Trucks", "KR", "C"),
  M("Tata Motors", "IN", "AUCB"),
  M("Mahindra", "IN", "AUT"),
  M("Maruti Suzuki", "IN", "A"),
  M("Hindustan Motors", "IN", "A", "D"),
  M("Force Motors", "IN", "U"),
  M("Ashok Leyland", "IN", "CB"),
  M("Eicher", "IN", "C"),
  M("Bajaj", "IN", "MQ"),
  M("TVS", "IN", "MQ"),
  M("Hero MotoCorp", "IN", "MQ"),
  M("Yezdi", "IN", "M", "R"),
  M("Ola Electric", "IN", "QE"),
  M("Ather", "IN", "QE"),
  M("Revolt", "IN", "ME"),
  M("Sonalika", "IN", "T"),
  M("Swaraj", "IN", "T"),
  M("Proton", "MY", "A"),
  M("Perodua", "MY", "A"),
  M("VinFast", "VN", "AE"),
  M("Esemka", "ID", "A"),
  M("Iran Khodro", "IR", "AB"),
  M("Saipa", "IR", "A"),
  M("Pars Khodro", "IR", "A"),
  M("BYD", "CN", "AEB"),
  M("Geely", "CN", "A"),
  M("Chery", "CN", "A"),
  M("Great Wall", "CN", "AU"),
  M("Haval", "CN", "A"),
  M("WEY", "CN", "AL"),
  M("Tank", "CN", "A"),
  M("ORA", "CN", "AE"),
  M("SAIC", "CN", "A"),
  M("Roewe", "CN", "A"),
  M("Maxus", "CN", "U"),
  M("Wuling", "CN", "AE"),
  M("Baojun", "CN", "A"),
  M("Changan", "CN", "A"),
  M("Deepal", "CN", "AE"),
  M("Avatr", "CN", "AE"),
  M("Dongfeng", "CN", "ACB"),
  M("Voyah", "CN", "AE"),
  M("GAC", "CN", "A"),
  M("Aion", "CN", "AE"),
  M("Hyptec", "CN", "AE"),
  M("Trumpchi", "CN", "A"),
  M("FAW", "CN", "AC"),
  M("Hongqi", "CN", "AL"),
  M("Bestune", "CN", "A"),
  M("BAIC", "CN", "A"),
  M("Beijing Auto", "CN", "A"),
  M("Foton", "CN", "UC"),
  M("JAC", "CN", "AU"),
  M("Jetour", "CN", "A"),
  M("NIO", "CN", "AE"),
  M("XPeng", "CN", "AE"),
  M("Li Auto", "CN", "A"),
  M("Zeekr", "CN", "AE"),
  M("Lynk & Co", "CN", "A"),
  M("Leapmotor", "CN", "AE"),
  M("Neta", "CN", "AE"),
  M("Aiways", "CN", "AE"),
  M("Seres", "CN", "AE"),
  M("DFSK", "CN", "AU"),
  M("Lifan", "CN", "AM"),
  M("Zotye", "CN", "A"),
  M("Brilliance", "CN", "A"),
  M("Jinbei", "CN", "U"),
  M("Haima", "CN", "A"),
  M("Weltmeister", "CN", "AE"),
  M("Jiyue", "CN", "AE"),
  M("Yangwang", "CN", "LE"),
  M("Fangchengbao", "CN", "A"),
  M("Denza", "CN", "LE"),
  M("Xiaomi Auto", "CN", "AE"),
  M("Aito", "CN", "AE"),
  M("Luxeed", "CN", "AE"),
  M("Skyworth", "CN", "AE"),
  M("Kaiyi", "CN", "A"),
  M("Soueast", "CN", "A"),
  M("Forthing", "CN", "A"),
  M("Radar", "CN", "UE"),
  M("Arcfox", "CN", "AE"),
  M("Rising Auto", "CN", "AE"),
  M("Yutong", "CN", "B"),
  M("King Long", "CN", "B"),
  M("Higer", "CN", "B"),
  M("Zhongtong", "CN", "B"),
  M("Ankai", "CN", "B"),
  M("Sany", "CN", "XC"),
  M("XCMG", "CN", "X"),
  M("Zoomlion", "CN", "X"),
  M("Liugong", "CN", "X"),
  M("Lonking", "CN", "X"),
  M("SDLG", "CN", "X"),
  M("Shacman", "CN", "C"),
  M("Sinotruk", "CN", "C"),
  M("JMC", "CN", "U"),
  M("CFMoto", "CN", "MV"),
  M("QJ Motor", "CN", "M"),
  M("Zongshen", "CN", "M"),
  M("Loncin", "CN", "M"),
  M("Haojue", "CN", "MQ"),
  M("Kymco", "TW", "QM"),
  M("SYM", "TW", "Q"),
  M("PGO", "TW", "Q"),
  M("Gogoro", "TW", "QE"),
  M("Aeon", "TW", "MV"),
  M("Ford", "US", "AUC"),
  M("Lincoln", "US", "AL"),
  M("Chevrolet", "US", "AU"),
  M("GMC", "US", "AUC"),
  M("Buick", "US", "AL"),
  M("Cadillac", "US", "AL"),
  M("Chrysler", "US", "A"),
  M("Dodge", "US", "AS"),
  M("Jeep", "US", "A"),
  M("Ram", "US", "U"),
  M("Plymouth", "US", "A", "D"),
  M("Pontiac", "US", "A", "D"),
  M("Oldsmobile", "US", "A", "D"),
  M("Saturn", "US", "A", "D"),
  M("Mercury", "US", "A", "D"),
  M("Hummer", "US", "A", "R"),
  M("Tesla", "US", "AE"),
  M("Rivian", "US", "AE"),
  M("Lucid", "US", "LE"),
  M("Fisker", "US", "AE", "D"),
  M("Karma", "US", "LE"),
  M("Faraday Future", "US", "AE"),
  M("Canoo", "US", "UE", "D"),
  M("Bollinger", "US", "UE"),
  M("Aptera", "US", "E"),
  M("Scout Motors", "US", "A", "R"),
  M("DeLorean", "US", "S", "D"),
  M("Tucker", "US", "A", "D"),
  M("Duesenberg", "US", "L", "D"),
  M("Packard", "US", "L", "D"),
  M("Studebaker", "US", "A", "D"),
  M("Nash", "US", "A", "D"),
  M("AMC", "US", "A", "D"),
  M("International", "US", "C"),
  M("Kenworth", "US", "C"),
  M("Peterbilt", "US", "C"),
  M("Freightliner", "US", "C"),
  M("Mack", "US", "C"),
  M("Western Star", "US", "C"),
  M("Autocar", "US", "C"),
  M("Oshkosh", "US", "CX"),
  M("Harley-Davidson", "US", "M"),
  M("Indian Motorcycle", "US", "M"),
  M("Victory Motorcycles", "US", "M", "D"),
  M("Buell", "US", "M", "D"),
  M("Polaris", "US", "V"),
  M("Arctic Cat", "US", "V"),
  M("Zero Motorcycles", "US", "ME"),
  M("LiveWire", "US", "ME"),
  M("Caterpillar", "US", "X"),
  M("John Deere", "US", "T"),
  M("Case IH", "US", "T"),
  M("New Holland", "US", "T"),
  M("Bobcat", "US", "X"),
  M("Hyster-Yale", "US", "X"),
  M("Terex", "US", "X"),
  M("Winnebago", "US", "R"),
  M("Airstream", "US", "R"),
  M("Thor", "US", "R"),
  M("Can-Am", "CA", "V"),
  M("BRP", "CA", "V"),
  M("Ski-Doo", "CA", "V"),
  M("Prevost", "CA", "B"),
  M("Nova Bus", "CA", "B"),
  M("New Flyer", "US", "B"),
  M("Blue Bird", "US", "B"),
  M("Vuhl", "MX", "S"),
  M("Mastretta", "MX", "S"),
  M("Agrale", "BR", "CT"),
  M("Marcopolo", "BR", "B"),
  M("Caio", "BR", "B"),
  M("Busscar", "BR", "B", "D"),
  M("Mascarello", "BR", "B"),
  M("Troller", "BR", "A", "D"),
  M("Gurgel", "BR", "A", "D"),
  M("Randon", "BR", "C"),
  M("Zanella", "AR", "M"),
  M("Holden", "AU", "A", "D"),
  M("HSV", "AU", "S", "D"),
  M("Elfin", "AU", "S"),
  M("Innoson Motors", "NG", "AUC"),
  M("Kantanka", "GH", "A"),
  M("Mobius Motors", "KE", "A"),
  M("Wallyscar", "TN", "V"),
  M("Laraki", "MA", "S"),
];

/** Énergies de propulsion (taxonomie générale, non vérifiée contre une norme). */
export const ENERGIES: string[] = [
  "Essence",
  "Diesel",
  "GPL",
  "GNV (gaz naturel)",
  "Éthanol / flex-fuel",
  "Hybride léger (micro / mild hybrid)",
  "Hybride (HEV)",
  "Hybride rechargeable (PHEV)",
  "Électrique à batterie (BEV)",
  "Électrique à prolongateur d'autonomie (EREV)",
  "Hydrogène (pile à combustible)",
  "Humaine assistée (vélo à assistance électrique)",
];

export const CARROSSERIES: string[] = [
  "Citadine",
  "Berline",
  "Break",
  "Coupé",
  "Cabriolet",
  "SUV",
  "Crossover",
  "4x4 / tout-terrain",
  "Monospace",
  "Pick-up",
  "Fourgon",
  "Fourgonnette",
  "Minibus",
  "Camion porteur",
  "Tracteur routier",
  "Autocar",
  "Autobus",
  "Moto routière",
  "Moto sportive",
  "Trail / enduro",
  "Custom / cruiser",
  "Roadster",
  "Scooter",
  "Cyclomoteur",
  "Quad / side-by-side",
  "Tricycle / trike",
  "Voiturette",
  "Camping-car",
  "Caravane",
  "Remorque",
  "Tracteur agricole",
  "Engin de chantier",
];

export const TRANSMISSIONS: string[] = ["Manuelle", "Automatique à convertisseur", "Robotisée (double embrayage / mono-embrayage)", "Variation continue (CVT)", "Réducteur simple (électrique)", "Transmission par chaîne (moto)", "Transmission par courroie (moto / scooter)", "Transmission par cardan (moto)", "Propulsion", "Traction", "Quatre roues motrices permanentes", "Quatre roues motrices enclenchables"];

export interface SystemePieces {
  code: string;
  libelle: string;
  familles: string[];
}

/**
 * Familles de pièces par système. Taxonomie générale (ce que l'on trouve sur un véhicule), pas un catalogue : aucune
 * référence constructeur, aucune compatibilité, aucun prix n'est affirmé ici. Les compatibilités viennent du catalogue
 * de pièces de la plateforme et des sources sous licence.
 */
export const SYSTEMES_PIECES: SystemePieces[] = [
  { code: "moteur", libelle: "Moteur thermique", familles: ["Bloc-moteur", "Culasse", "Joint de culasse", "Pistons et segments", "Bielles", "Vilebrequin", "Arbres à cames", "Soupapes et guides", "Poussoirs hydrauliques", "Carter d'huile", "Coussinets", "Volant moteur / volant bimasse", "Supports moteur"] },
  { code: "distribution", libelle: "Distribution, admission et échappement", familles: ["Kit de distribution (courroie ou chaîne)", "Galet tendeur et enrouleur", "Pompe à eau", "Collecteur d'admission", "Boîtier papillon", "Turbocompresseur", "Compresseur volumétrique", "Échangeur d'air (intercooler)", "Collecteur d'échappement", "Catalyseur", "Filtre à particules (FAP)", "Vanne EGR", "Sonde lambda", "Silencieux et ligne d'échappement", "Système SCR / AdBlue"] },
  { code: "lubrification", libelle: "Lubrification et filtration", familles: ["Huile moteur", "Filtre à huile", "Pompe à huile", "Radiateur d'huile", "Filtre à air", "Filtre à carburant", "Filtre d'habitacle"] },
  { code: "refroidissement", libelle: "Refroidissement", familles: ["Radiateur", "Thermostat", "Durites", "Vase d'expansion", "Motoventilateur", "Liquide de refroidissement", "Calorstat"] },
  { code: "alimentation", libelle: "Alimentation en carburant et injection", familles: ["Pompe à carburant", "Injecteurs", "Rampe d'injection", "Pompe haute pression", "Réservoir et jauge", "Carburateur (anciens modèles et motos)", "Régulateur de pression"] },
  { code: "allumage", libelle: "Allumage et préchauffage", familles: ["Bougies d'allumage", "Bobines d'allumage", "Faisceau d'allumage", "Bougies de préchauffage", "Relais de préchauffage"] },
  { code: "transmission", libelle: "Embrayage et transmission", familles: ["Kit d'embrayage", "Butée et émetteur / récepteur d'embrayage", "Boîte de vitesses", "Boîte automatique", "Mécatronique de boîte", "Différentiel", "Arbres de transmission et cardans", "Soufflets de cardan", "Boîte de transfert", "Pont", "Huile de boîte"] },
  { code: "freinage", libelle: "Freinage", familles: ["Plaquettes de frein", "Disques de frein", "Tambours et mâchoires", "Étriers de frein", "Maître-cylindre", "Servofrein", "Flexibles et durites de frein", "Capteurs ABS", "Bloc hydraulique ABS / ESP", "Frein de stationnement (câble ou électrique)", "Liquide de frein"] },
  { code: "direction", libelle: "Direction", familles: ["Crémaillère de direction", "Pompe de direction assistée", "Colonne de direction", "Rotules de direction", "Biellettes de direction", "Direction assistée électrique"] },
  { code: "suspension", libelle: "Suspension et liaison au sol", familles: ["Amortisseurs", "Ressorts hélicoïdaux", "Coupelles et butées d'amortisseur", "Triangles et bras de suspension", "Silentblocs", "Barres stabilisatrices et biellettes", "Rotules de suspension", "Roulements de roue et moyeux", "Suspension pneumatique", "Lames de ressort (utilitaires et camions)"] },
  { code: "roues", libelle: "Roues et pneumatiques", familles: ["Pneus été", "Pneus hiver", "Pneus toutes saisons", "Jantes", "Capteurs de pression des pneus (TPMS)", "Écrous et boulons de roue", "Chambres à air (moto, vélo)", "Kits de réparation"] },
  { code: "carrosserie", libelle: "Carrosserie et vitrage", familles: ["Pare-chocs", "Ailes", "Capots", "Portes", "Hayon et coffre", "Boucliers et renforts", "Rétroviseurs", "Pare-brise et vitres", "Joints et caoutchoucs", "Calandre", "Bas de caisse", "Essuie-glaces et moteurs", "Serrures et poignées", "Lève-vitres"] },
  { code: "eclairage", libelle: "Éclairage et signalisation", familles: ["Phares avant", "Feux arrière", "Feux antibrouillard", "Clignotants", "Ampoules (halogène, xénon, LED)", "Troisième feu stop", "Avertisseur sonore", "Feux de jour"] },
  { code: "electricite", libelle: "Électricité et électronique", familles: ["Batterie 12 V", "Alternateur", "Démarreur", "Faisceaux électriques", "Fusibles et relais", "Calculateur moteur (ECU)", "Calculateurs de confort et de carrosserie", "Capteurs (vilebrequin, arbre à cames, température, pression)", "Débitmètre d'air", "Commodos et contacteurs", "Combiné d'instruments", "Autoradio et écran multimédia", "Antennes", "Clés et télécommandes"] },
  { code: "climatisation", libelle: "Chauffage et climatisation", familles: ["Compresseur de climatisation", "Condenseur", "Évaporateur", "Détendeur", "Radiateur de chauffage", "Pulseur d'air", "Fluide frigorigène", "Résistance de chauffage"] },
  { code: "interieur", libelle: "Habitacle et sécurité passive", familles: ["Sièges", "Ceintures de sécurité", "Airbags et prétensionneurs", "Tableau de bord", "Garnitures de porte", "Tapis", "Volant", "Console centrale", "Ciel de toit"] },
  { code: "adas", libelle: "Aides à la conduite (ADAS) et capteurs", familles: ["Caméra de pare-brise", "Radar avant", "Capteurs de recul", "Radar d'angle mort", "Caméra de recul / 360°", "Capteur de pluie et de luminosité", "Calibrage ADAS (opération)"] },
  { code: "electrique", libelle: "Électrique et hybride", familles: ["Batterie haute tension", "Moteur électrique", "Onduleur", "Chargeur embarqué", "Convertisseur DC/DC", "Câbles et prises de recharge", "Unité de gestion de batterie (BMS)", "Pompe à chaleur", "Refroidissement de batterie", "Réducteur électrique"] },
  { code: "moto", libelle: "Spécifique moto, scooter et quad", familles: ["Chaîne, pignon et couronne", "Kit chaîne", "Courroie de transmission (scooter)", "Variateur et galets", "Embrayage centrifuge", "Carénages", "Selle", "Guidon et leviers", "Fourche et amortisseur arrière", "Frein à disque moto", "Pneus moto", "Échappement moto", "Carburateur ou injection moto", "Batterie moto", "Casque et équipement du pilote"] },
  { code: "poids_lourds", libelle: "Spécifique utilitaires, camions et bus", familles: ["Freinage à air comprimé", "Compresseur d'air", "Sécheur d'air", "Ralentisseur (frein moteur auxiliaire)", "Sellette d'attelage", "Chronotachygraphe", "Rampes de chargement et hayons élévateurs", "Réservoir AdBlue", "Filtres à gazole renforcés", "Boîte robotisée poids lourd"] },
  { code: "entretien", libelle: "Consommables et entretien courant", familles: ["Huiles et lubrifiants", "Liquides (frein, refroidissement, lave-glace)", "Filtres", "Courroies d'accessoires", "Balais d'essuie-glace", "Ampoules", "Produits de nettoyage et de protection", "Graisses et colles"] },
  { code: "accessoires", libelle: "Accessoires et équipements", familles: ["Attelages et faisceaux", "Barres de toit et coffres de toit", "Porte-vélos", "Tapis et protections", "Alarmes et traceurs", "Dashcams", "Chargeurs et câbles", "Housses et bâches", "Équipements de sécurité (triangle, gilet, extincteur)"] },
];
