CREATE TABLE IF NOT EXISTS "gv_dependencies" (
	"id" serial PRIMARY KEY NOT NULL,
	"provider_id" varchar(48) NOT NULL UNIQUE,
	"internal_name" varchar(120) NOT NULL,
	"category" varchar(32) DEFAULT 'ia_modele' NOT NULL,
	"adapter_id" varchar(160) NOT NULL,
	"capabilities_available" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"capabilities_used" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"authentication_type" varchar(40) DEFAULT 'api_key' NOT NULL,
	"fallback" text DEFAULT '' NOT NULL,
	"alternative_provider" varchar(48),
	"data_dependency" text DEFAULT '' NOT NULL,
	"internal_replacement" varchar(160) DEFAULT '' NOT NULL,
	"internal_replacement_status" varchar(40) DEFAULT 'external_primary' NOT NULL,
	"migration_priority" varchar(16) DEFAULT 'moyenne' NOT NULL,
	"target_disconnect_date" timestamp,
	"last_independence_test" timestamp,
	"last_independence_test_ok" boolean,
	"training_rights" varchar(24) DEFAULT 'LEGAL_RIGHTS_UNKNOWN' NOT NULL,
	"redistribution_rights" varchar(24) DEFAULT 'LEGAL_RIGHTS_UNKNOWN' NOT NULL,
	"retention_policy" text DEFAULT '' NOT NULL,
	"cache_policy" text DEFAULT '' NOT NULL,
	"country_constraints" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" varchar(32) DEFAULT 'REGISTERED' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
