/**
 * Mémoire de l'IA — projets, recherche, décisions et leçons des 1er et 2 octobre 2026.
 *
 * Demande du PDG (2 octobre 2026) : remplir les mémoires encore vides avec tout ce qui est réellement établi. Chaque entrée
 * vient de ce qui a été fait ou demandé pendant ces deux jours (PR et documents cités), dit l'état réel et ce qui reste, et
 * ne contient aucune donnée inventée. Posées une fois au démarrage (même principe que fondations.ts) : une clé déjà active
 * n'est jamais réécrite ; une correction est un nouveau souvenir sous la même clé (l'ancien devient l'historique).
 */
import { and, eq } from "drizzle-orm";
import { db } from "../db.js";
import { inMemoire } from "./schema.js";
import { ecrire } from "./memoire.js";

interface SouvenirTravaux {
  categorie: "projets" | "recherche" | "decisions" | "apprentissage";
  cle: string;
  titre: string;
  contenu: string;
  liens: Record<string, string>;
}

export const SOUVENIRS_TRAVAUX: SouvenirTravaux[] = [
  { categorie: "projets", cle: "projet-finalisation-produits-cars4kids-02-10-2026", titre: "Finalisation des produits Cars4Kids (boutique) — état au 2 octobre 2026", contenu: "Périmètre fixé par le PDG : produits, photos, stock, colis, livraison, panier — rien d'autre. Fait (mkapms-shop, fusionné) : archive des photos originales fournisseur et version premium MKA.P-MS avec contrôle de marque (PR #72) ; stock en direct qui ne dépublie plus la fiche, colis par SKU, base fiscale de livraison hors TVA pour Cars4Kids, registre de TVA sans aucun taux livré, devis de panier public, contrôle de bout en bout d'un produit réel (PR #73) ; panier de la vitrine branché sur le devis du serveur (PR #74) ; outils gouvernés de l'IA de la boutique et moteur de panier (PR #71). Reste, de la part du PDG ou à vérifier : redéploiement de la boutique ; taux de TVA par pays avec leur source ; base fiscale TTC/HT par produit ; référence des droits photo Cars4Kids (sans elle les photos restent bloquées « droits manquants ») ; réimport du fichier produits si l'import date d'avant le 2 octobre ; vérification de bout en bout sur un vrai produit ; achats publics toujours fermés (aucun paiement, aucune commande).", liens: {"depot": "mkapms-shop", "pr": "71-74", "doc": "docs/SHOP-LIVE-STOCK-CART-2026-10-02.md ; docs/SHOP-PRODUCT-PHOTOS-2026-10-02.md"} },
  { categorie: "projets", cle: "projet-connexion-ia-principale-boutique-02-10-2026", titre: "Connexion de l'IA principale à la boutique — état au 2 octobre 2026", contenu: "Décision du PDG : l'IA principale travaille dans la boutique (photos, détails des fiches) tant que l'IA de la boutique n'est pas prête ; sens unique (la boutique n'appelle jamais la plateforme principale). Fait : jeton de service côté boutique (créé par le Fondateur avec mot de passe et MFA, portées catalogue.read / photos.work / drafts.propose, expiration, révocation, journal) — mkapms-shop PR #75 ; cinq outils boutique.* côté plateforme, entrée « Boutique » du Coffre, copie datée de la mémoire de la boutique — mkapms-web PR #532. Reste : redéploiement des deux applications ; création du jeton dans la boutique et dépôt dans le Coffre (« Boutique — jeton de service », « Boutique — adresse ») ; droits d'image du fournisseur enregistrés dans la boutique ; premier appel réel à constater (aucun n'a été fait). Jamais possible avec ce jeton : prix, TVA, stock, livraison, approbation, publication.", liens: {"depot": "mkapms-shop, mkapms-web", "pr": "shop #75, web #532"} },
  { categorie: "projets", cle: "projet-micros-voix-02-10-2026", titre: "Micros et voix de l'interface — état au 2 octobre 2026", contenu: "Micro bleu (conversation vocale) : fonctionne ; l'erreur d'ouverture « invalid_offer » venait d'une offre WebRTC sans saut de ligne final (corrigée, PR #530) ; la transcription échouait en « model_not_found » car le projet du fournisseur n'autorisait pas le modèle demandé : repli automatique de modèle et mémorisation du modèle qui a écrit (PR #531 et #534). Voix : toutes les voix du mode direct avec écoute d'un extrait (PR #531). Micro gris (dictée en direct dans le champ de saisie) : NON diagnostiqué, en attente d'une capture d'écran du PDG. Limite connue : le service ne rend le texte d'une phrase qu'à la fin de celle-ci, parler sans pause retarde donc le texte. À faire côté PDG : autoriser un modèle de transcription dans le projet OpenAI de la clé.", liens: {"pr": "web #530, #531, #534"} },
  { categorie: "projets", cle: "projet-memoire-automobile-referentiel-02-10-2026", titre: "Mémoire automobile : référentiel des marques, types de véhicules et familles de pièces", contenu: "Demande du PDG (2 octobre 2026) : remplir la mémoire automobile avec toutes les marques du monde (voitures, motos, camions, bus, utilitaires, engins, y compris les marques récentes) et les pièces nécessaires. Posé : un référentiel de départ (plus de quatre cents marques notables, anciennes et actuelles, avec pays d'origine, catégories et état), des catégories de véhicules, énergies, carrosseries, transmissions, et les familles de pièces par système ; tout en connaissance générale NON vérifiée (statut « proposé »). Source réelle ajoutée : la liste des marques enregistrées auprès de la NHTSA (API publique, plus de douze mille noms, États-Unis seulement), synchronisée au démarrage puis au plus une fois par mois. Limites assumées : aucune liste n'est exhaustive à l'échelle mondiale ; les modèles, motorisations, années, groupes propriétaires et compatibilités de pièces ne sont PAS inscrits (ils exigent une source datée) ; les marques créées aujourd'hui n'apparaissent qu'à mesure que les sources les reconnaissent. Suite proposée : modèles et motorisations par marque via une source sous licence ou documentée, compatibilités depuis le catalogue de pièces de la plateforme.", liens: {"pr": "web (mémoire automobile)", "source": "server/knowledge-engine/referentiel-automobile.ts ; nhtsa.ts"} },
  { categorie: "projets", cle: "projet-annonce-depuis-photo-et-plaque-02-10-2026", titre: "Annonce prête à publier à partir d'une photo et d'une plaque — état au 2 octobre 2026", contenu: "Objectif du PDG (ou d'un professionnel) : envoyer la photo d'un véhicule avec sa plaque et obtenir une annonce complète placée « prête à publier », automatiquement. Ce qui existe : le moteur véhicule (server/vehicle-engine) enchaîne ingestion, normalisation, détection de doublons, analyse, contrôle qualité, analyse IA, calcul du prix, territoires, disponibilité, puis « prêt à publier » (READY_TO_PUBLISH) ; la publication reste une décision humaine (validerEtPublier). Ce qui manque : (1) lire la plaque et en tirer les données officielles du véhicule — aucune API de ce type n'est connectée aujourd'hui ; (2) un outil de l'IA qui, depuis une photo et une plaque, remplit la fiche et lance ce pipeline ; (3) la reconnaissance du véhicule sur la photo est possible par la lecture d'image du modèle, mais ses déductions (marque, modèle, couleur, état) restent à confirmer et ne remplacent pas les données officielles. Règles qui ne bougent pas : aucune donnée inventée (année, kilométrage, puissance, historique), prix calculé par le moteur de prix, jamais proposé par le modèle ; publication décidée par un humain. Décision attendue du PDG : pays prioritaires pour la plaque et choix du fournisseur de données (voir la mémoire recherche).", liens: {"moteur": "vehicle_engine", "statut": "cadrage — non construit"} },
  { categorie: "projets", cle: "projet-autonomie-ia-chat-travail-02-10-2026", titre: "Autonomie de l'IA et séparation Chat / Travail — état au 2 octobre 2026", contenu: "Décision du PDG : l'IA travaille en autonomie (un ordre donné, elle l'exécute, cherche d'autres solutions si un moyen échoue, vise un résultat premium) ; Chat et Travail partagent la même mémoire et la même fonction, le Chat renseigne et planifie sans agir, le Travail exécute. Fait : section « Autonomie de travail » de la consigne direction ; boucle d'outils portée à 12 tours ; Chat sans outil qui agit ; moteur de l'Agent développeur réparé (il lui manquait la permission d'analyser) ; un objectif sur la boutique passe en Travail par la boucle d'outils (PR #533, #534). Limites inchangées : rien d'inventé, ni publication, approbation, paiement, déploiement, ni modification de prix, TVA, stock ou livraison ; aucun secret en conversation. Reste : constater le comportement réel après déploiement (aucun essai avec un vrai modèle dans l'environnement de développement) ; le curseur d'autonomie du Centre Intelligences reste le réglage du PDG.", liens: {"pr": "web #533, #534"} },
  { categorie: "projets", cle: "projet-publication-applications-android-02-10-2026", titre: "Publication des applications Android — état au 2 octobre 2026", contenu: "Le workflow GitHub « Android — App Bundles » construit les paquets ; la signature utilise un trousseau fourni hors du dépôt ; les outils GitHub de l'IA sont en lecture seule (vérifier la connexion, voir les exécutions) et utilisent le jeton déposé dans le Coffre sous « GitHub — jeton mkapms-web ». Le moteur ne signe, ne publie et ne déploie rien. Reste côté PDG : dépôt du jeton GitHub et des éléments Google Play dans le Coffre ; vérification de l'état réel de chaque fiche dans Play Console avant toute action.", liens: {"source": "connaissances « publication » de la base de connaissances"} },
  { categorie: "projets", cle: "projet-tva-boutique-02-10-2026", titre: "TVA de la boutique — taux à fournir avec leur source", contenu: "Le registre de TVA de la boutique existe mais ne contient aucun taux : aucun n'est livré avec le code et aucun ne doit être deviné. Tant qu'un pays n'a pas de taux enregistré avec sa source, le panier affiche « TVA à confirmer » et « Total indisponible » plutôt qu'un total approximatif. À fournir par le PDG (ou son comptable) : taux par pays de destination avec la source, et la base fiscale (TTC ou HT) du prix de vente de chaque produit.", liens: {"depot": "mkapms-shop", "doc": "docs/SHOP-LIVE-STOCK-CART-2026-10-02.md"} },
  { categorie: "recherche", cle: "recherche-lecture-plaque-donnees-vehicule-02-10-2026", titre: "Lire une plaque d'immatriculation et en tirer les données du véhicule — pistes non décidées", contenu: "Besoin : à partir d'une plaque, obtenir marque, modèle, énergie, puissance, date de première mise en circulation. Pistes, aucune choisie, aucune testée : (a) source officielle nationale — l'accès dépend du pays et est souvent réservé à des professionnels habilités ; (b) interface commerciale par pays qui revend ces données ; (c) bases automobiles sous licence. Critères de choix à établir avec le PDG : pays prioritaires, droit de conserver et de republier les données, coût par requête, qualité et date des données, conformité aux règles de protection des données du pays. Tant qu'aucune source n'est connectée, l'IA ne doit jamais déduire ces données d'une photo comme si elles étaient officielles.", liens: {"statut": "à décider"} },
  { categorie: "recherche", cle: "recherche-transcription-en-direct-sans-pause-02-10-2026", titre: "Texte en direct quand on parle sans s'arrêter — pistes non testées", contenu: "Constat : avec la détection de fin de phrase du service vocal, le texte d'une phrase n'arrive qu'après un silence. Pistes : valider des segments à intervalles réguliers côté navigateur pendant que la personne parle ; utiliser un modèle de transcription qui renvoie des fragments au fil de l'eau ; utiliser la reconnaissance vocale intégrée au navigateur pour l'affichage en direct. Aucune n'a été essayée : chacune peut avoir des effets (coupures de mots, doublons, coût) à constater en conditions réelles avant adoption.", liens: {"statut": "à tester"} },
  { categorie: "recherche", cle: "recherche-exhaustivite-marques-modeles-02-10-2026", titre: "Couvrir toutes les marques et tous les modèles du monde — ce qui existe et ses limites", contenu: "Aucune source gratuite unique connue ne couvre toutes les marques et tous les modèles du monde. Sources identifiées : la liste NHTSA (marques enregistrées aux États-Unis, publique, mais des marques européennes et chinoises y manquent) ; la documentation des constructeurs (à utiliser selon leurs conditions) ; des bases automobiles sous licence (accès payant, droits à lire) ; la veille de la plateforme (découvertes soumises à décision du PDG). Une marque absente de toutes ces sources n'est pas connue de la mémoire : le dire plutôt que la deviner. Aucune année, aucun groupe propriétaire ni aucune compatibilité de pièce ne s'inscrit sans source datée.", liens: {"statut": "en cours — voir projet mémoire automobile"} },
  { categorie: "recherche", cle: "recherche-taux-tva-sources-officielles-02-10-2026", titre: "Sources possibles pour les taux de TVA par pays — à vérifier", contenu: "Les taux de TVA doivent venir d'une source officielle datée, jamais d'une mémoire du modèle. Pistes non vérifiées ici : la base de taxation publiée par la Commission européenne pour les pays de l'Union ; les administrations fiscales de chaque pays hors Union. À faire avant tout enregistrement : confirmer la source, la date de validité et le cas particulier des livraisons transfrontalières avec le comptable du PDG.", liens: {"statut": "à vérifier"} },
  { categorie: "decisions", cle: "decision-ia-principale-dans-boutique-sens-unique-02-10-2026", titre: "2 octobre 2026 — l'IA principale travaille dans la boutique, sens unique", contenu: "Le PDG demande que l'IA principale se connecte à la boutique et y fasse le travail (images, détails des produits) tant que l'IA de la boutique n'est pas prête, et qu'il discute avec elle en direct. Décision d'architecture associée : la plateforme principale appelle la boutique, jamais l'inverse ; jeton créé par le Fondateur, portées explicites, expiration, révocation, journal ; ni prix, ni TVA, ni stock, ni livraison, ni approbation, ni publication. La décision du 27 septembre (la boutique reste autonome, sa propre clé) est conservée.", liens: {"source": "Demande du PDG, 2 octobre 2026 ; AGENTS.md de mkapms-shop"} },
  { categorie: "decisions", cle: "decision-autonomie-totale-avec-limites-02-10-2026", titre: "2 octobre 2026 — autonomie de travail de l'IA, limites conservées", contenu: "Le PDG veut une IA qui, une fois l'ordre donné, l'exécute directement, trouve des solutions par tout moyen disponible et vise un résultat premium. Retenu : exécution directe avec les outils actifs, enchaînement jusqu'au résultat, solution de repli, compte rendu final. Conservé : aucune donnée inventée ; ni publication, approbation, paiement, déploiement, ni modification de prix, TVA, stock, livraison ; aucun secret dans la conversation ; le curseur d'autonomie du Centre Intelligences reste le réglage du PDG.", liens: {"source": "Demande du PDG, 2 octobre 2026"} },
  { categorie: "decisions", cle: "decision-chat-travail-meme-memoire-02-10-2026", titre: "2 octobre 2026 — Chat et Travail : même mémoire, même fonction", contenu: "Le PDG décide que le Chat et le Travail partagent la même mémoire et la même fonction ; le Chat sert à se renseigner et à obtenir des indications et des plans, le Travail à exécuter. Dans le Chat aucun outil qui agit n'est disponible ; en Travail tous les outils actifs le sont.", liens: {"source": "Demande du PDG, 2 octobre 2026"} },
  { categorie: "decisions", cle: "decision-memoire-travaux-automatique-02-10-2026", titre: "2 octobre 2026 — les travaux et conversations de travail enrichissent la mémoire", contenu: "Le PDG étant le seul utilisateur pour l'instant, les tâches et les conversations de travail faites avec lui enrichissent automatiquement la mémoire (fonction « Mémoire des travaux et conversations », allumée par défaut, désactivable). Jamais d'échange trivial ni d'échange contenant un secret ; jamais bloquant pour la réponse.", liens: {"source": "Demande du PDG, 2 octobre 2026"} },
  { categorie: "decisions", cle: "decision-memoire-automobile-sourcee-02-10-2026", titre: "2 octobre 2026 — remplir la mémoire automobile, sans rien inventer", contenu: "Le PDG demande de remplir la mémoire automobile avec toutes les marques du monde et les pièces nécessaires, et d'indiquer les API à connecter si besoin. Retenu : un référentiel de départ marqué non vérifié, une source publique réelle synchronisée (NHTSA), la provenance obligatoire sur chaque fait, et la liste des sources manquantes communiquée au PDG plutôt que des données inventées.", liens: {"source": "Demande du PDG, 2 octobre 2026"} },
  { categorie: "decisions", cle: "decision-secrets-coffre-illimite-02-10-2026", titre: "2 octobre 2026 — le Coffre accepte autant de secrets que nécessaire", contenu: "Le PDG veut pouvoir ajouter et supprimer à volonté des secrets de tout type (jetons Railway, clés d'autres boutiques ou d'autres API, informations fournisseurs) depuis le Coffre secret, avec un bouton « Ajouter ». Fait (PR #531). Les secrets ne passent jamais par la conversation.", liens: {"source": "Demande du PDG, 2 octobre 2026"} },
  { categorie: "apprentissage", cle: "lecon-stock-synchronise-depubliait-la-fiche-02-10-2026", titre: "Une synchronisation de stock retirait la fiche de la vitrine", contenu: "Problème : « rupture = fiche conservée, indisponible » et « retour en stock = réactivation automatique » étaient impossibles. Diagnostic : chaque synchronisation de stock modifiait la date de l'offre et la révision du catalogue, deux valeurs auxquelles la publication était liée ; la fiche sortait donc de la vitrine à chaque synchronisation. Solution : la publication est liée aux conditions de l'offre (prix, devise, preuve), jamais au stock ; la disponibilité se lit en direct. Résultat : prouvé par un test de bout en bout (rupture puis retour en stock sans republication). Leçon : un identifiant de version doit changer pour la bonne raison ; lier une autorisation à une donnée qui bouge sans cesse la révoque sans que personne ne l'ait décidé.", liens: {"pr": "shop #73"} },
  { categorie: "apprentissage", cle: "lecon-moteur-sans-permission-arret-agent-02-10-2026", titre: "Un moteur sans permission arrête toute mission dès l'analyse", contenu: "Problème : en mode Travail, la moindre demande aboutissait à « Permission ANALYZE exigée : le moteur intelligences_orchestrateur ne l'a pas reçue ». Diagnostic : ce moteur n'avait aucune ligne dans la table des permissions par moteur et héritait seulement de READ ; son étape d'analyse passe par le routeur de capacités qui exige ANALYZE. Solution : lui attribuer ANALYZE et PROPOSE, rien de plus. Résultat : test sur les permissions exactes du moteur. Leçon : tout moteur qui appelle le routeur porte lui-même les permissions de ses étapes, sinon la première étape qui dépasse la lecture échoue, quel que soit le rôle de la personne.", liens: {"pr": "web #534"} },
  { categorie: "apprentissage", cle: "lecon-modele-transcription-refuse-02-10-2026", titre: "Un modèle nommé en dur peut être absent de l'allocation du projet", contenu: "Problème : le micro captait mais rien ne s'écrivait (« model_not_found »), puis les premières phrases de chaque session se perdaient. Diagnostic : le projet du fournisseur n'autorisait pas le modèle de transcription demandé ; le repli automatique ne s'activait qu'après un premier échec, à chaque nouvelle session. Solution : repli ordonné de modèles, message clair si aucun n'est autorisé, et mémorisation du modèle qui a réellement écrit pour la session suivante. Résultat : tests simulés ; non vérifié en conditions réelles. Leçon : retenir ce qui a marché plutôt que perdre les premiers essais à chaque fois, et dire quoi autoriser plutôt qu'afficher un code.", liens: {"pr": "web #531, #534"} },
  { categorie: "apprentissage", cle: "lecon-protocole-octet-pour-octet-02-10-2026", titre: "Une donnée de protocole se transmet octet pour octet", contenu: "Problème : le micro vocal échouait à l'ouverture avec « invalid_offer ». Diagnostic : le code nettoyait l'offre WebRTC avec un trim() avant l'envoi, ce qui supprimait le saut de ligne final exigé par la norme du format SDP ; un analyseur strict le refuse. Solution : valider sur une copie nettoyée, transmettre un SDP complet (fins de ligne CRLF, dernière comprise). Résultat : prouvé avec un analyseur SDP strict. Leçon : ne jamais nettoyer « par précaution » une donnée de protocole, de signature ou d'en-tête.", liens: {"pr": "web #530"} },
  { categorie: "apprentissage", cle: "lecon-mot-de-passe-prix-jamais-au-service-02-10-2026", titre: "Donner un accès à une IA : portées explicites et interdits d'abord", contenu: "Problème : permettre à l'IA principale de travailler dans la boutique sans lui ouvrir ce qui doit rester au PDG. Solution : jeton créé par le propriétaire, empreinte seule stockée, expiration, révocation, portées explicites ; les routes des gestes interdits (prix, TVA, stock, livraison, approbation, publication) n'existent pas pour ce jeton ; chaque appel est journalisé sous un acteur propre. Résultat : test d'intégration, dont une mutation volontaire des portées qui fait échouer le test. Leçon : définir d'abord ce qui est interdit, puis ce qui est permis, et vérifier qu'un test échoue vraiment quand on retire la protection.", liens: {"pr": "shop #75"} },
];

export async function seedSouvenirsTravaux(): Promise<{ nouveaux: number; total: number }> {
  let nouveaux = 0;
  for (const s of SOUVENIRS_TRAVAUX) {
    const [existant] = await db
      .select({ id: inMemoire.id })
      .from(inMemoire)
      .where(and(eq(inMemoire.categorie, s.categorie), eq(inMemoire.cle, s.cle), eq(inMemoire.cycle, "actif")))
      .limit(1);
    if (existant) continue;
    await ecrire({ categorie: s.categorie, cle: s.cle, titre: s.titre, contenu: s.contenu, liens: s.liens, source: "fondations-travaux" });
    nouveaux += 1;
  }
  return { nouveaux, total: SOUVENIRS_TRAVAUX.length };
}
