import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Car, CheckCircle2, ClipboardCheck, FileText, Package, ShieldCheck, ShoppingCart, Truck, Warehouse, Search, CircleHelp, Store, Plus, Minus } from "lucide-react";
import { trpc } from "../lib/trpc";
import { addPieceToCart } from "../lib/piecesCartStore";
import { useReportNavigation } from "../lib/redirect";

export default function PiecesProduit() {
  const id = Number(useParams().id);
  const navigate = useNavigate();
  const signaler = useReportNavigation();
  const [quantity, setQuantity] = useState(1);
  const [plaque, setPlaque] = useState("");
  const [vin, setVin] = useState("");
  const part = trpc.pieces.part.useQuery({ id }, { enabled: Number.isInteger(id) && id > 0 });
  if (part.isLoading) return <div className="container-page py-12 text-slate-500">Chargement de la pièce…</div>;
  if (!part.data) return <div className="container-page py-12"><Link className="btn-outline" to="/pieces">Retour au catalogue</Link><p className="mt-5 text-slate-600">Cette pièce n’est plus disponible.</p></div>;
  const p = part.data;
  const add = () => {
    for (let i = 0; i < quantity; i++) addPieceToCart({ catalogId: p.id, nom: p.nom, prixHt: Number(p.prixHt), currency: p.currency, shopId: p.shopId });
    signaler("pieces_panier", "/pieces?panier=1");
    navigate("/pieces?panier=1");
  };
  return <div className="container-page max-w-7xl bg-white py-4 pb-28">
    <div className="flex items-center justify-between border-b border-slate-100 pb-3"><Link to="/pieces" className="shrink-0"><img src="/brand/wordmark.png" alt="MKA.P-MS" className="h-9 w-auto"/></Link><button onClick={add} className="btn-gold flex items-center gap-2 !px-3 !py-2 text-sm"><ShoppingCart size={17}/> Panier</button></div>
    <nav className="mt-3 flex overflow-x-auto rounded-lg border border-slate-100 bg-slate-50 p-1 text-sm font-bold"><Link to="/pieces" className="min-w-max flex-1 rounded-md px-4 py-2 text-center text-slate-700">▣ Catalogue</Link><Link to="/pieces?onglet=boutique" className="min-w-max flex-1 rounded-md px-4 py-2 text-center text-slate-700">▦ Boutique</Link><Link to="/pieces?onglet=commandes" className="min-w-max flex-1 rounded-md px-4 py-2 text-center text-slate-700">▤ Mes commandes</Link><Link to="/pieces?onglet=suivi" className="min-w-max flex-1 rounded-md px-4 py-2 text-center text-slate-700">◌ Suivi</Link></nav>
    <p className="mt-4 text-xs text-slate-500">Catalogue › {p.categorie ?? "Pièces"} › {p.nom}</p>
    <Link to="/pieces" className="mt-2 inline-flex items-center gap-2 text-sm font-semibold text-[#0d7391] hover:text-gold-dark"><ArrowLeft size={16}/> Retour au catalogue</Link>
    <h1 className="mt-3 text-2xl font-extrabold tracking-tight text-slate-950">{p.nom}</h1><p className="mt-1 text-xs text-slate-500">Référence {p.referenceInterne}{p.referenceOem ? ` · OEM ${p.referenceOem}` : ''}</p>
    <div className="mt-3 grid gap-6 lg:grid-cols-[1.25fr_.75fr]">
      <section className="card overflow-hidden p-4"><div className="grid aspect-[4/3] place-items-center rounded-xl bg-slate-100 text-slate-400">{p.photoUrl ? <img src={p.photoUrl} alt={p.nom} className="h-full w-full object-contain"/> : <><Package size={72}/><span className="mt-3 text-xs">Illustration de produit indisponible</span></>}</div><p className="mt-3 text-xs text-slate-400">Les visuels et prix sont fournis par le vendeur.</p></section>
      <aside className="card h-fit p-5"><div className="rounded-xl bg-[#fff7dd] p-4"><p className="text-3xl font-extrabold text-slate-900">{Number(p.prixTtc ?? p.prixHt).toLocaleString("fr-FR")} {p.currency} <span className="text-sm font-semibold">TTC</span></p><p className="mt-1 text-xs text-slate-500">Prix affiché à l’unité · {Number(p.prixHt).toLocaleString("fr-FR")} {p.currency} HT</p></div><p className="mt-4 flex items-center gap-2 text-sm font-semibold"><Warehouse size={17} className="text-emerald-600"/>{p.stockDisponible > 0 ? `${p.stockDisponible} en stock` : "Disponibilité à confirmer"}</p><div className="mt-4 flex items-center gap-3"><label className="text-sm font-semibold">Quantité</label><button aria-label="Diminuer" className="rounded border px-2" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={14}/></button><span>{quantity}</span><button aria-label="Augmenter" className="rounded border px-2" onClick={() => setQuantity(quantity + 1)}><Plus size={14}/></button></div><button onClick={add} className="btn-gold mt-5 w-full" disabled={p.stockDisponible <= 0}><ShoppingCart size={18} className="mr-2 inline"/>Ajouter au panier</button><button onClick={() => navigate("/livraison")} className="btn-outline mt-2 w-full"><Truck size={16} className="mr-2 inline"/>Calculer la livraison</button><p className="mt-4 border-t pt-3 text-xs text-slate-500"><Store size={14} className="mr-1 inline"/>Vendeur : MKA.P‑MS · Informations vendeur et facture disponibles à la commande.</p></aside>
    </div>
    <section className="mt-6 overflow-hidden rounded-xl border border-[#d4af37]/30 bg-[#fffdf7]"><div className="flex items-center gap-2 bg-[#f7f2e5] px-4 py-3"><Car className="text-[#0d7391]" size={21}/><div><h2 className="font-extrabold">Cette pièce convient-elle à votre véhicule ?</h2><p className="text-xs text-slate-500">Vérifiez la plaque ou le VIN avant montage.</p></div></div><div className="grid gap-2 p-3 sm:grid-cols-[.8fr_1fr_1fr_auto]"><select className="input !py-2" defaultValue="FR" aria-label="Pays"><option value="FR">🇫🇷 France</option></select><input className="input !py-2" value={plaque} onChange={e=>setPlaque(e.target.value.toUpperCase())} placeholder="AA-123-AA"/><input className="input !py-2" value={vin} onChange={e=>setVin(e.target.value.toUpperCase())} placeholder="VIN / châssis"/><Link to={`/pieces?plaque=${encodeURIComponent(plaque)}&vin=${encodeURIComponent(vin)}`} className="btn-gold flex items-center justify-center gap-2 !py-2"><Search size={16}/> Vérifier</Link></div></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-3"><div className="card p-5 lg:col-span-2"><h2 className="text-lg font-extrabold text-noir">Description du produit</h2><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600">{p.description || "La description technique sera communiquée par le vendeur avant commande."}</p><h2 className="mt-7 text-lg font-extrabold text-noir">Caractéristiques techniques</h2><dl className="mt-3 grid grid-cols-2 overflow-hidden rounded-lg border text-sm"><dt className="bg-slate-50 p-3 font-semibold">Type</dt><dd className="p-3">{p.condition}</dd><dt className="bg-slate-50 p-3 font-semibold">Référence OEM</dt><dd className="p-3">{p.referenceOem ?? "Non renseignée"}</dd><dt className="bg-slate-50 p-3 font-semibold">Dimensions</dt><dd className="p-3">{[p.longueurCm && `${p.longueurCm} cm`, p.largeurCm && `${p.largeurCm} cm`, p.hauteurCm && `${p.hauteurCm} cm`].filter(Boolean).join(" × ") || "Non renseignées"}</dd><dt className="bg-slate-50 p-3 font-semibold">Poids</dt><dd className="p-3">{p.poidsKg ? `${p.poidsKg} kg` : "Non renseigné"}</dd></dl></div><div className="space-y-4"><div className="card p-5"><h2 className="flex items-center gap-2 font-extrabold"><Car size={18} className="text-gold-dark"/> Compatibilité</h2><p className="mt-2 text-sm text-slate-600">Plaque, VIN, modèle et motorisation restent disponibles à chaque étape.</p><Link to="/pieces" className="btn-outline mt-4 w-full">Identifier un véhicule</Link></div><div className="card p-5"><h2 className="font-extrabold">Documents et services</h2><Link to="/pieces/retours-pieces" className="mt-3 flex items-center gap-2 text-sm font-semibold text-slate-700"><ShieldCheck size={16}/> Garantie et retours</Link><Link to="/livraison" className="mt-3 flex items-center gap-2 text-sm font-semibold text-slate-700"><Truck size={16}/> Livraison</Link><Link to="/aide" className="mt-3 flex items-center gap-2 text-sm font-semibold text-slate-700"><FileText size={16}/> Besoin d’aide</Link></div></div></section>
    <section className="mt-6 rounded-xl border border-info/20 bg-info/5 p-4 text-sm text-slate-700"><ClipboardCheck size={17} className="mr-2 inline text-info"/>Comparez la référence, les dimensions et la compatibilité véhicule avant de commander.</section>
    <section className="mt-8 grid gap-2 border-y border-slate-100 py-4 sm:grid-cols-3"><Link to="/livraison" className="rounded-lg p-3 text-sm hover:bg-slate-50"><Truck size={18} className="mr-2 inline text-[#0d7391]"/><b>Livraison suivie</b><small className="mt-1 block text-slate-500">Choix du mode et suivi après commande</small></Link><Link to="/pieces/retours-pieces" className="rounded-lg p-3 text-sm hover:bg-slate-50"><ShieldCheck size={18} className="mr-2 inline text-[#0d7391]"/><b>Garanties et retours</b><small className="mt-1 block text-slate-500">Conditions accessibles avant achat</small></Link><Link to="/aide" className="rounded-lg p-3 text-sm hover:bg-slate-50"><CircleHelp size={18} className="mr-2 inline text-[#0d7391]"/><b>Besoin d’aide ?</b><small className="mt-1 block text-slate-500">Assistance et informations techniques</small></Link></section>
    <footer className="mt-6 rounded-xl bg-slate-950 px-5 py-6 text-sm text-slate-300"><div className="grid gap-5 sm:grid-cols-3"><div><img src="/brand/wordmark.png" alt="MKA.P-MS" className="h-8 brightness-0 invert"/><p className="mt-2 text-xs text-slate-400">Boutique pièces de la plateforme principale MKA.P‑MS.</p></div><div><b className="text-white">Mes achats</b><div className="mt-2 grid gap-1 text-xs"><Link to="/pieces?onglet=commandes">Mes commandes</Link><Link to="/pieces?onglet=suivi">Suivi de mes services</Link><Link to="/pieces/retours-pieces">Retours et garanties</Link></div></div><div><b className="text-white">Informations</b><div className="mt-2 grid gap-1 text-xs"><Link to="/livraison">Livraison</Link><Link to="/aide">Aide et contact</Link><Link to="/confidentialite">Confidentialité</Link></div></div></div><p className="mt-5 border-t border-white/10 pt-3 text-xs text-slate-500">© {new Date().getFullYear()} MKA.P‑MS · Références, dimensions et compatibilités à vérifier avant montage.</p></footer>
  </div>;
}
