/**
 * MKA.P-MS — portail public « près de moi ».
 * Les annuaires Garage, Comptabilité et Pièces gardent leurs pages et moteurs
 * propres : cet écran ne fait que guider le visiteur vers le bon portail.
 */
import { Link } from "react-router-dom";
import { ArrowRight, Building2, CheckCircle2, Clock3, MapPin, Navigation, Search, ShieldCheck, Sparkles } from "lucide-react";
import { trpc } from "../lib/trpc";

const SERVICE_STYLES: Record<string, { icon: React.ReactNode; description: string }> = {
  garage: { icon: <Building2 size={20} />, description: "Trouver un garage, demander un devis ou préparer un rendez-vous." },
  comptable: { icon: <CheckCircle2 size={20} />, description: "Accéder au centre comptable et à son annuaire vérifié." },
  pieces: { icon: <Search size={20} />, description: "Explorer les pièces et les professionnels spécialisés." },
  controle_technique: { icon: <ShieldCheck size={20} />, description: "Préparer votre contrôle et découvrir le service dédié." },
  depannage: { icon: <Navigation size={20} />, description: "Accéder à l’assistance et au parcours dépannage." },
  livraison: { icon: <ArrowRight size={20} />, description: "Organiser une livraison avec le portail transport." },
  vtc_taxi: { icon: <MapPin size={20} />, description: "Découvrir les solutions VTC et Taxi." },
  location: { icon: <Clock3 size={20} />, description: "Voir les véhicules et solutions de location." },
};

export default function PresDeMoi() {
  const services = trpc.proximity.services.useQuery();

  return <main className="min-h-screen overflow-hidden bg-[#F5F7FB] pb-14 text-[#111827]">
    <section className="relative isolate overflow-hidden bg-[#101824] px-4 pb-28 pt-9 text-white sm:px-6 sm:pb-32 sm:pt-12">
      <div className="absolute inset-0 -z-20 bg-[radial-gradient(circle_at_78%_15%,rgba(0,134,255,.37),transparent_31%),radial-gradient(circle_at_16%_82%,rgba(255,215,0,.16),transparent_35%)]" />
      <div className="absolute -right-20 top-5 -z-10 h-80 w-80 rounded-full border border-sky-200/15" /><div className="absolute -right-9 top-14 -z-10 h-80 w-80 rounded-full border border-sky-200/10" />
      <div className="mx-auto max-w-6xl text-center"><Link to="/services" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2 text-xs font-bold text-white/85 backdrop-blur transition hover:border-[#FFD700] hover:bg-white/15"><ArrowRight size={14} className="rotate-180" /> Retour aux services</Link><div className="mx-auto mt-9 inline-flex items-center gap-2 rounded-full border border-[#FFD700]/50 bg-[#FFD700]/10 px-3 py-2 text-[10px] font-black uppercase tracking-[.16em] text-[#FFE891]"><Navigation size={14} /> Portails de proximité MKA.P-MS</div><h1 className="mx-auto mt-5 max-w-4xl text-4xl font-black leading-[1.03] tracking-tight sm:text-6xl">Le bon portail, au bon moment.</h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-white/80 sm:text-base">Choisissez votre besoin. Chaque accès vous emmène vers l’univers MKA.P-MS adapté, avec ses propres outils, informations et parcours sécurisé.</p><div className="mt-7 flex flex-wrap justify-center gap-2 text-xs font-bold text-white/90"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2"><ShieldCheck size={14} className="text-[#FFE891]" /> Accès officiels</span><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2"><CheckCircle2 size={14} className="text-[#7FD3FF]" /> Parcours vérifiés</span><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2"><Clock3 size={14} className="text-[#FFE891]" /> Disponible 24h/24</span></div></div>
    </section>

    <section className="relative z-10 mx-auto -mt-16 max-w-6xl px-4 sm:-mt-20 sm:px-6" aria-labelledby="portals-title"><div className="rounded-[30px] border border-white/90 bg-white p-5 shadow-[0_24px_60px_rgba(5,12,22,.18)] sm:p-7"><div className="border-b border-slate-100 pb-5 text-center"><p className="text-xs font-black uppercase tracking-[.14em] text-[#087BA8]">Vos portails de service</p><h2 id="portals-title" className="mt-1 text-2xl font-black tracking-tight text-[#111827] sm:text-3xl">Où souhaitez-vous aller ?</h2><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-slate-500">Un accès clair par besoin : aucun faux résultat ni annuaire inventé. Les pages existantes restent intactes et vous y êtes redirigé directement.</p></div>
      {services.isLoading ? <div className="flex items-center justify-center py-14 text-sm font-semibold text-slate-500"><Sparkles className="mr-2 h-5 w-5 animate-pulse text-[#087BA8]" /> Préparation de vos portails…</div> : <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(services.data ?? []).map((service) => { const style = SERVICE_STYLES[service.code] ?? { icon: <Building2 size={20} />, description: "Accéder à ce service MKA.P-MS." }; return <Link key={service.code} to={service.path} className="group flex min-h-56 flex-col rounded-[24px] border border-slate-200 bg-white p-5 text-center shadow-[0_8px_20px_rgba(17,17,17,.04)] transition hover:-translate-y-1 hover:border-[#7FD3FF] hover:shadow-[0_18px_36px_rgba(0,134,255,.12)]"><span className={`mx-auto grid h-12 w-12 place-items-center rounded-2xl ${service.localisable ? "bg-[#0086FF]/10 text-[#087BA8]" : "bg-[#FFD700]/15 text-[#B8860B]"}`}>{style.icon}</span><h3 className="mt-4 text-base font-black text-[#111827]">{service.label}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{style.description}</p><span className="mt-auto inline-flex items-center justify-center gap-2 pt-5 text-sm font-black text-[#087BA8]">Ouvrir le portail <ArrowRight size={16} className="transition group-hover:translate-x-1" /></span></Link>; })}</div>}
    </div></section>

    <section className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><div className="grid gap-4 md:grid-cols-3"><TrustCard icon={<ShieldCheck size={21} />} title="Clarté avant tout" text="Chaque carte ouvre le vrai univers concerné. Les pages, données et moteurs déjà en place ne sont pas modifiés ici." tone="blue" /><TrustCard icon={<MapPin size={21} />} title="Une proximité responsable" text="La géolocalisation et les distances ne sont utilisées que dans les portails réellement équipés pour les traiter." tone="gold" /><TrustCard icon={<CheckCircle2 size={21} />} title="Un parcours fiable" text="Les accès sont organisés par besoin pour aller plus vite, sans confusion entre vos services ni promesse non vérifiable." tone="blue" /></div></section>

    <section className="border-y border-[#FFD700]/20 bg-white px-4 py-10 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex flex-col items-center gap-5 rounded-[28px] bg-[#101824] p-6 text-center text-white sm:p-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.14em] text-[#FFE891]">Vous êtes professionnel ?</p><h2 className="mt-2 text-2xl font-black">Faites connaître votre activité sur MKA.P-MS.</h2><p className="mt-2 text-sm leading-6 text-white/70">Préparez votre dossier depuis votre espace professionnel. Les informations visibles restent soumises aux contrôles de la plateforme.</p></div><Link to="/espace-pro" className="inline-flex w-full max-w-sm items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#0086FF] to-[#006AD1] px-5 py-3 text-sm font-black text-white shadow-[0_10px_24px_rgba(0,134,255,.28)] transition hover:from-[#1294FF] hover:to-[#0874D9]">Référencer mon activité <ArrowRight size={17} /></Link></div></div></section>

    <footer className="mx-auto max-w-6xl px-4 py-9 text-center sm:px-6"><p className="text-sm font-black text-[#111827]">MKA.P-MS <span className="text-[#B8860B]">Proximité</span></p><p className="mx-auto mt-3 max-w-3xl text-xs leading-6 text-slate-500">MKA.P-MS vous redirige vers le bon portail. Les conditions, informations et contrôles propres à chaque service restent affichés dans son univers.</p><div className="mt-4 flex flex-wrap justify-center gap-x-5 gap-y-2 text-xs font-bold text-[#087BA8]"><Link to="/confiance">Centre de confiance</Link><Link to="/confidentialite">Confidentialité</Link><Link to="/aide">Aide & questions</Link></div></footer>
  </main>;
}

function TrustCard({ icon, title, text, tone }: { icon: React.ReactNode; title: string; text: string; tone: "blue" | "gold" }) { return <article className="rounded-3xl border border-slate-100 bg-white p-6 text-center shadow-[0_8px_20px_rgba(17,17,17,.03)]"><span className={`mx-auto grid h-11 w-11 place-items-center rounded-2xl ${tone === "blue" ? "bg-[#0086FF]/10 text-[#087BA8]" : "bg-[#FFD700]/15 text-[#B8860B]"}`}>{icon}</span><h2 className="mt-4 text-base font-black text-[#111827]">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
