/**
 * Sommaire des sections dont la page d'accueil est générique, et état réel
 * de leurs écrans.
 *
 * Fichier GÉNÉRÉ par scripts/gen-sections.mjs depuis client/src/App.tsx.
 * Ne pas éditer à la main : `npm run gen:sections` le régénère, et la
 * construction échoue s'il est périmé.
 *
 * Sert à deux choses : rendre la section atteignable (page d'accueil réelle
 * listant ses écrans), et dire au Système Intelligent combien d'écrans sont
 * encore des gabarits vides au lieu de les compter comme livrés.
 */
export interface EntreeSection {
  readonly chemin: string;
  readonly titre: string;
  /** Gabarit « Module … » : l'écran existe mais n'affiche aucun contenu. */
  readonly vide: boolean;
}

export interface SectionSommaire {
  readonly prefixe: string;
  readonly titre: string;
  readonly entrees: readonly EntreeSection[];
}

export const SECTIONS_SOMMAIRE: readonly SectionSommaire[] = [
  {
    prefixe: "/automatisations",
    titre: "Automatisations",
    entrees: [
      { chemin: "/automatisations/centre-alertes-strategiques", titre: "Alertes stratégiques", vide: true },
      { chemin: "/automatisations/centre-auto-marketing", titre: "Automatisation marketing", vide: true },
      { chemin: "/automatisations/centre-croissance", titre: "Centre croissance", vide: true },
      { chemin: "/automatisations/centre-k-p-i", titre: "Centre KPI", vide: true },
      { chemin: "/automatisations/centre-objectifs-entreprise", titre: "Centre objectifs", vide: true },
      { chemin: "/automatisations/escalades-automatiques", titre: "Escalades automatiques", vide: true },
      { chemin: "/automatisations/files-attente", titre: "Files attente", vide: true },
      { chemin: "/automatisations/i-a-affectation", titre: "Intelligence affectation", vide: true },
      { chemin: "/automatisations/i-a-controle", titre: "Intelligence de contrôle", vide: true },
      { chemin: "/automatisations/i-a-priorisation", titre: "Intelligence de priorisation", vide: true },
      { chemin: "/automatisations/moteur-taches", titre: "Moteur de tâches", vide: true },
      { chemin: "/automatisations/moteur-workflow", titre: "Moteur de workflow", vide: true },
      { chemin: "/automatisations/objectif-automatisations", titre: "Objectif automatisations", vide: true },
      { chemin: "/automatisations/centre-performance-i-a", titre: "Performance Intelligence", vide: true },
      { chemin: "/automatisations/workflows-personnalises", titre: "Workflows personnalisés", vide: true },
    ],
  },
  {
    prefixe: "/communaute",
    titre: "Communauté",
    entrees: [
      { chemin: "/communaute/avis-conseils", titre: "Avis et Conseils", vide: true },
      { chemin: "/communaute/guides-achat", titre: "Guides achat", vide: true },
      { chemin: "/communaute/guides-garage", titre: "Guides garage", vide: true },
      { chemin: "/communaute/guides-location", titre: "Guides location", vide: true },
      { chemin: "/communaute/guides-vente", titre: "Guides vente", vide: true },
      { chemin: "/communaute/questions-reponses", titre: "Questions et Réponses", vide: true },
    ],
  },
  {
    prefixe: "/conformite",
    titre: "Conformité",
    entrees: [
      { chemin: "/conformite/assurances-pays", titre: "Assurances par pays", vide: true },
      { chemin: "/conformite/centre-pays", titre: "Centre pays", vide: true },
      { chemin: "/conformite/contrats-adaptes", titre: "Contrats adaptés", vide: true },
      { chemin: "/conformite/devises-automatiques", titre: "Devises automatiques", vide: true },
      { chemin: "/conformite/documents-obligatoires-pays", titre: "Documents obligatoires par pays", vide: true },
      { chemin: "/conformite/garage-pays", titre: "Garage par pays", vide: true },
      { chemin: "/conformite/immatriculations-pays", titre: "Immatriculations par pays", vide: true },
      { chemin: "/conformite/i-a-juridique", titre: "Intelligence juridique", vide: true },
      { chemin: "/conformite/location-pays", titre: "Location par pays", vide: true },
      { chemin: "/conformite/mises-a-jour-reglementaires", titre: "Mises à jour réglementaires", vide: true },
      { chemin: "/conformite/moteur-regles-pays", titre: "Moteur règles pays", vide: true },
      { chemin: "/conformite/moyens-paiement-locaux", titre: "Moyens de paiement locaux", vide: true },
      { chemin: "/conformite/objectif-conformite", titre: "Objectif conformité", vide: true },
      { chemin: "/conformite/tableau-bord-international", titre: "Tableau de bord international", vide: true },
      { chemin: "/conformite/taxes-automatiques", titre: "Taxes automatiques", vide: true },
      { chemin: "/conformite/vente-pays", titre: "Vente par pays", vide: true },
    ],
  },
  {
    prefixe: "/corporate",
    titre: "L'entreprise MKA.P-MS",
    entrees: [
      { chemin: "/corporate/a-propos", titre: "À propos", vide: true },
      { chemin: "/corporate/contact-entreprise", titre: "Contact entreprise", vide: true },
      { chemin: "/corporate/nos-partenaires", titre: "Nos partenaires", vide: true },
      { chemin: "/corporate/nos-services", titre: "Nos services", vide: true },
      { chemin: "/corporate/presse-actualites", titre: "Presse et Actualités", vide: true },
      { chemin: "/corporate/vision-m-k-a-p-m-s", titre: "Vision MKA.P-MS", vide: true },
    ],
  },
  {
    prefixe: "/entreprises",
    titre: "Entreprises et flottes",
    entrees: [
      { chemin: "/entreprises/centre-carburant", titre: "Centre carburant", vide: true },
      { chemin: "/entreprises/centre-geolocalisation", titre: "Centre géolocalisation", vide: true },
      { chemin: "/entreprises/centre-immobilisation", titre: "Centre immobilisation", vide: true },
      { chemin: "/entreprises/compte-flotte", titre: "Compte flotte entreprise", vide: true },
      { chemin: "/entreprises/contrats-entreprises", titre: "Contrats entreprises", vide: true },
      { chemin: "/entreprises/gestion-conducteurs", titre: "Gestion conducteurs", vide: true },
      { chemin: "/entreprises/gestion-parc", titre: "Gestion parc automobile", vide: true },
      { chemin: "/entreprises/historique-flotte", titre: "Historique flotte", vide: true },
      { chemin: "/entreprises/objectif-flottes", titre: "Objectif flottes", vide: true },
      { chemin: "/entreprises/rapports-entreprises", titre: "Rapports entreprises", vide: true },
    ],
  },
  {
    prefixe: "/expansion",
    titre: "Expansion internationale",
    entrees: [
      { chemin: "/expansion/centre-international", titre: "Centre international", vide: true },
      { chemin: "/expansion/multi-devises-global", titre: "Multi-devises global", vide: true },
      { chemin: "/expansion/multi-langues-global", titre: "Multi-langues global", vide: true },
      { chemin: "/expansion/phase-france", titre: "Phase 1 — France", vide: true },
      { chemin: "/expansion/phase-amerique-latine", titre: "Phase 10 — Amérique Latine", vide: true },
      { chemin: "/expansion/phase-asie", titre: "Phase 11 — Asie", vide: true },
      { chemin: "/expansion/phase-oceanie", titre: "Phase 12 — Océanie", vide: true },
      { chemin: "/expansion/phase-europe-franco", titre: "Phase 2 — Europe francophone", vide: true },
      { chemin: "/expansion/phase-europe", titre: "Phase 3 — Europe", vide: true },
      { chemin: "/expansion/phase-afrique-ouest", titre: "Phase 4 — Afrique de l Ouest", vide: true },
      { chemin: "/expansion/phase-afrique-centrale", titre: "Phase 5 — Afrique Centrale", vide: true },
      { chemin: "/expansion/phase-afrique-nord", titre: "Phase 6 — Afrique du Nord", vide: true },
      { chemin: "/expansion/phase-afrique-est", titre: "Phase 7 — Afrique de l Est", vide: true },
      { chemin: "/expansion/phase-moyen-orient", titre: "Phase 8 — Moyen-Orient", vide: true },
      { chemin: "/expansion/phase-amerique-nord", titre: "Phase 9 — Amérique du Nord", vide: true },
      { chemin: "/expansion/tableau-bord-mondial", titre: "Tableau de bord mondial", vide: true },
      { chemin: "/expansion/vision-finale", titre: "Vision finale MKA.P-MS", vide: true },
    ],
  },
  {
    prefixe: "/formations",
    titre: "Formations",
    entrees: [
      { chemin: "/formations/certificats", titre: "Certificats", vide: true },
      { chemin: "/formations/formation-garage", titre: "Formation garage", vide: true },
      { chemin: "/formations/formation-taxi", titre: "Formation taxi", vide: true },
      { chemin: "/formations/formation-vente", titre: "Formation vente automobile", vide: true },
      { chemin: "/formations/formation-v-t-c", titre: "Formation VTC", vide: true },
    ],
  },
  {
    prefixe: "/ia",
    titre: "MKA.P-MS Intelligences",
    entrees: [
      { chemin: "/ia/i-a-aide-devis", titre: "Intelligence Aide au devis", vide: true },
      { chemin: "/ia/i-a-analyse-marche", titre: "Intelligence Analyse marché", vide: true },
      { chemin: "/ia/i-a-assistant-client", titre: "Intelligence Assistant client", vide: true },
      { chemin: "/ia/i-a-detection-fraude", titre: "Intelligence Détection fraude", vide: true },
      { chemin: "/ia/i-a-estimation", titre: "Intelligence Estimation", vide: true },
    ],
  },
  {
    prefixe: "/international",
    titre: "International",
    entrees: [
      { chemin: "/international/multi-devises", titre: "Multi-devises", vide: true },
      { chemin: "/international/multi-langues", titre: "Multi-langues", vide: true },
      { chemin: "/international/multi-pays", titre: "Multi-pays", vide: true },
    ],
  },
  {
    prefixe: "/labs",
    titre: "Laboratoires MKA.P-MS",
    entrees: [
      { chemin: "/labs/academie-m-k-a-p-m-s", titre: "Académie MKA.P-MS", vide: true },
      { chemin: "/labs/analyse-marche-mondiale", titre: "Analyse marché mondiale", vide: true },
      { chemin: "/labs/analyse-trafic", titre: "Analyse trafic", vide: true },
      { chemin: "/labs/archives-historiques", titre: "Archives historiques", vide: true },
      { chemin: "/labs/assistant-fondateur", titre: "Assistant fondateur", vide: true },
      { chemin: "/labs/audit-qualite", titre: "Audit qualité", vide: true },
      { chemin: "/labs/automatisation-complete", titre: "Automatisation complète", vide: true },
      { chemin: "/labs/benchmark-flottes", titre: "Benchmark flottes", vide: true },
      { chemin: "/labs/bibliotheque-automobile", titre: "Bibliothèque automobile mondiale", vide: true },
      { chemin: "/labs/bibliotheque-reparations", titre: "Bibliothèque réparations", vide: true },
      { chemin: "/labs/brevets", titre: "Brevets et innovations", vide: true },
      { chemin: "/labs/campus-automobile", titre: "Campus automobile", vide: true },
      { chemin: "/labs/carnet-entretien-auto", titre: "Carnet entretien automatique", vide: true },
      { chemin: "/labs/cartographie-mondiale", titre: "Cartographie mondiale", vide: true },
      { chemin: "/labs/centre-acquisitions-labs", titre: "Centre acquisitions", vide: true },
      { chemin: "/labs/centre-appels-offres", titre: "Centre appels offres", vide: true },
      { chemin: "/labs/centre-coordination-mondial", titre: "Centre coordination mondial", vide: true },
      { chemin: "/labs/centre-documentation", titre: "Centre documentation", vide: true },
      { chemin: "/labs/centre-donnees-mondiales", titre: "Centre données mondiales", vide: true },
      { chemin: "/labs/centre-expansion-auto", titre: "Centre expansion automatique", vide: true },
      { chemin: "/labs/centre-expansion-automatique2", titre: "Centre expansion automatique", vide: true },
      { chemin: "/labs/centre-export-auto", titre: "Centre export automobile", vide: true },
      { chemin: "/labs/centre-formation-afrique", titre: "Centre formation Afrique", vide: true },
      { chemin: "/labs/centre-innovation", titre: "Centre innovation", vide: true },
      { chemin: "/labs/centre-intelligence-marche", titre: "Centre intelligence marché", vide: true },
      { chemin: "/labs/centre-investissements-labs", titre: "Centre investissements", vide: true },
      { chemin: "/labs/centre-opportunites-mondiales", titre: "Centre opportunités mondiales", vide: true },
      { chemin: "/labs/centre-recherche-m-k-a-p-m-s", titre: "Centre recherche", vide: true },
      { chemin: "/labs/centre-recherche-auto", titre: "Centre recherche automobile", vide: true },
      { chemin: "/labs/centre-strategie-groupe", titre: "Centre stratégie groupe", vide: true },
      { chemin: "/labs/centre-traduction", titre: "Centre traduction", vide: true },
      { chemin: "/labs/logistiques-centres", titre: "Centres logistiques", vide: true },
      { chemin: "/labs/centres-mobilite-urbaine", titre: "Centres mobilité urbaine", vide: true },
      { chemin: "/labs/centres-reconditionnement", titre: "Centres reconditionnement", vide: true },
      { chemin: "/labs/centres-reconditionnement2", titre: "Centres reconditionnement réseau", vide: true },
      { chemin: "/labs/centres-techniques", titre: "Centres techniques", vide: true },
      { chemin: "/labs/certification-occasion", titre: "Certification occasion", vide: true },
      { chemin: "/labs/certification-vehicule", titre: "Certification véhicule", vide: true },
      { chemin: "/labs/coffrefort-international", titre: "Coffre-fort international", vide: true },
      { chemin: "/labs/conferences-internationales", titre: "Conférences internationales", vide: true },
      { chemin: "/labs/controle-distance-flottes", titre: "Contrôle à distance flottes", vide: true },
      { chemin: "/labs/controle-production", titre: "Contrôle production", vide: true },
      { chemin: "/labs/corridors-logistiques", titre: "Corridors logistiques", vide: true },
      { chemin: "/labs/data-cloud-auto", titre: "Data Cloud automobile", vide: true },
      { chemin: "/labs/centre-decisions-strategiques", titre: "Décisions stratégiques", vide: true },
      { chemin: "/labs/encyclopedie-automobile", titre: "Encyclopédie automobile mondiale", vide: true },
      { chemin: "/labs/expansion-mondiale", titre: "Expansion mondiale", vide: true },
      { chemin: "/labs/filiales", titre: "Filiales", vide: true },
      { chemin: "/labs/fleet-network-mondial", titre: "Fleet Network mondial", vide: true },
      { chemin: "/labs/fondation-formation", titre: "Fondation formation", vide: true },
      { chemin: "/labs/fondation-mobilite", titre: "Fondation mobilité", vide: true },
      { chemin: "/labs/fonds-developpement", titre: "Fonds développement", vide: true },
      { chemin: "/labs/fonds-developpement2", titre: "Fonds développement", vide: true },
      { chemin: "/labs/fonds-expansion-afrique", titre: "Fonds expansion Afrique", vide: true },
      { chemin: "/labs/fonds-innovation", titre: "Fonds innovation", vide: true },
      { chemin: "/labs/formations-certifiantes", titre: "Formations certifiantes", vide: true },
      { chemin: "/labs/franchise-m-k-a-p-m-s", titre: "Franchise MKA.P-MS", vide: true },
      { chemin: "/labs/franchises-global", titre: "Franchises", vide: true },
      { chemin: "/labs/energy-batteries", titre: "Gestion batteries", vide: true },
      { chemin: "/labs/gestion-entrepots", titre: "Gestion entrepôts", vide: true },
      { chemin: "/labs/gestion-flotte-intelligente", titre: "Gestion flotte intelligente", vide: true },
      { chemin: "/labs/gestion-flottes-connectees", titre: "Gestion flottes connectees", vide: true },
      { chemin: "/labs/gestion-groupe", titre: "Gestion groupe", vide: true },
      { chemin: "/labs/gestion-marques", titre: "Gestion marques", vide: true },
      { chemin: "/labs/gestion-mobilite-entreprises", titre: "Gestion mobilité entreprises", vide: true },
      { chemin: "/labs/hub-afrique", titre: "Hub Afrique", vide: true },
      { chemin: "/labs/hubs-regionaux", titre: "Hubs régionaux", vide: true },
      { chemin: "/labs/identite-numerique-entreprise", titre: "Identité numérique entreprise", vide: true },
      { chemin: "/labs/identite-numerique-vehicule", titre: "Identité numérique véhicule", vide: true },
      { chemin: "/labs/identite-numerique-vehicule2", titre: "Identité numérique véhicule — suivi à vie", vide: true },
      { chemin: "/labs/inspection-distance", titre: "Inspection à distance", vide: true },
      { chemin: "/labs/i-a-automobile", titre: "Intelligence automobile", vide: true },
      { chemin: "/labs/i-a-avancee", titre: "Intelligence avancée", vide: true },
      { chemin: "/labs/i-a-conseiller-achat", titre: "Intelligence conseiller achat", vide: true },
      { chemin: "/labs/i-a-conseiller-garage", titre: "Intelligence conseiller garage", vide: true },
      { chemin: "/labs/i-a-conseiller-vente", titre: "Intelligence conseiller vente", vide: true },
      { chemin: "/labs/i-a-operationnelle-mondiale", titre: "Intelligence opérationnelle mondiale", vide: true },
      { chemin: "/labs/jumeau-numerique", titre: "Jumeau numérique", vide: true },
      { chemin: "/labs/jumeau-numerique-mondial", titre: "Jumeau numérique mondial", vide: true },
      { chemin: "/labs/jumeaux-numeriques", titre: "Jumeaux numériques véhicules", vide: true },
      { chemin: "/labs/label-certifie", titre: "Label MKA.P-MS Certifié", vide: true },
      { chemin: "/labs/label-mondial", titre: "Label mondial", vide: true },
      { chemin: "/labs/laboratoires-futurs", titre: "Laboratoires futurs", vide: true },
      { chemin: "/labs/licences-m-k-a-p-m-s", titre: "Licences MKA.P-MS", vide: true },
      { chemin: "/labs/maintenance-predictive", titre: "Maintenance prédictive", vide: true },
      { chemin: "/labs/energy-recharge", titre: "MKA.P-MS Energy — Recharge", vide: false },
      { chemin: "/labs/future2050", titre: "MKA.P-MS Future 2050+", vide: true },
      { chemin: "/labs/global-standards", titre: "MKA.P-MS Global Standards", vide: true },
      { chemin: "/labs/institut-formation", titre: "MKA.P-MS Institute — Formation internationale", vide: true },
      { chemin: "/labs/m-k-a-p-m-s-world", titre: "MKA.P-MS World", vide: true },
      { chemin: "/labs/world-vision", titre: "MKA.P-MS World Vision", vide: true },
      { chemin: "/labs/mobilite-complete", titre: "Mobilité complète", vide: true },
      { chemin: "/labs/musee-numerique", titre: "Musée numérique MKA.P-MS", vide: true },
      { chemin: "/labs/norme-m-k-a-p-m-s", titre: "Norme MKA.P-MS Certification", vide: true },
      { chemin: "/labs/objectif-ultime", titre: "Objectif ultime MKA.P-MS", vide: true },
      { chemin: "/labs/observatoire-automobile", titre: "Observatoire automobile", vide: true },
      { chemin: "/labs/observatoire-mondial", titre: "Observatoire mondial", vide: true },
      { chemin: "/labs/parc-industriel", titre: "Parc industriel", vide: true },
      { chemin: "/labs/passeport-numerique-vehicule", titre: "Passeport numérique véhicule", vide: true },
      { chemin: "/labs/place-marche-b2-b", titre: "Place de marché B2B", vide: true },
      { chemin: "/labs/programme-innovation", titre: "Programme innovation", vide: true },
      { chemin: "/labs/programme-jeunes-entrepreneurs", titre: "Programme jeunes entrepreneurs", vide: true },
      { chemin: "/labs/programmes-strategiques", titre: "Programmes stratégiques", vide: true },
      { chemin: "/labs/reseau-alliances", titre: "Réseau alliances internationales", vide: true },
      { chemin: "/labs/reseau-assistance247", titre: "Réseau assistance 24/7", vide: true },
      { chemin: "/labs/reseau-centres-formation", titre: "Réseau centres formation mondial", vide: true },
      { chemin: "/labs/reseau-convoyeurs", titre: "Réseau convoyeurs", vide: true },
      { chemin: "/labs/reseau-depannage-afrique", titre: "Réseau dépannage Afrique", vide: true },
      { chemin: "/labs/reseau-depanneurs", titre: "Réseau dépanneurs", vide: true },
      { chemin: "/labs/reseau-distribution", titre: "Réseau distribution", vide: true },
      { chemin: "/labs/energy-afrique", titre: "Réseau énergie Afrique", vide: true },
      { chemin: "/labs/reseau-experts", titre: "Réseau experts", vide: true },
      { chemin: "/labs/reseau-experts-global", titre: "Réseau experts global", vide: true },
      { chemin: "/labs/reseau-fournisseurs-global", titre: "Réseau fournisseurs global", vide: true },
      { chemin: "/labs/reseau-garages-afrique", titre: "Réseau garages Afrique", vide: true },
      { chemin: "/labs/reseau-industriel", titre: "Réseau industriel", vide: true },
      { chemin: "/labs/reseau-mobilite-mondiale", titre: "Réseau mobilité mondiale", vide: true },
      { chemin: "/labs/reseau-mondial-complet", titre: "Réseau mondial complet", vide: true },
      { chemin: "/labs/reseau-mondial-partenaires", titre: "Réseau mondial partenaires", vide: true },
      { chemin: "/labs/reseau-mondial-services", titre: "Réseau mondial services", vide: true },
      { chemin: "/labs/reseau-pieces-afrique", titre: "Réseau pièces Afrique", vide: true },
      { chemin: "/labs/reseau-transport", titre: "Réseau transport", vide: true },
      { chemin: "/labs/reseau-transport-marchandises", titre: "Réseau transport marchandises", vide: true },
      { chemin: "/labs/reseau-transport-personnes", titre: "Réseau transport personnes", vide: true },
      { chemin: "/labs/reseau-usines", titre: "Réseau usines", vide: true },
      { chemin: "/labs/signature-universelle", titre: "Signature universelle", vide: true },
      { chemin: "/labs/smart-vehicles", titre: "Smart Vehicles", vide: true },
      { chemin: "/labs/stationnement-intelligent", titre: "Stationnement intelligent", vide: true },
      { chemin: "/labs/systemes-proprietaires", titre: "Systèmes propriétaires", vide: true },
      { chemin: "/labs/telematique", titre: "Télématique", vide: true },
      { chemin: "/labs/tests-pilotes", titre: "Tests pilotes", vide: true },
      { chemin: "/labs/vehicules-connectes", titre: "Vehicules connectes", vide: true },
      { chemin: "/labs/vision-finale-m-k-a-p-m-s", titre: "Vision finale MKA.P-MS", vide: true },
      { chemin: "/labs/zones-techniques", titre: "Zones techniques", vide: true },
    ],
  },
  {
    prefixe: "/marketing",
    titre: "Marketing",
    entrees: [
      { chemin: "/marketing/campagnes-automatiques", titre: "Campagnes automatiques", vide: true },
      { chemin: "/marketing/codes-promotionnels", titre: "Codes promotionnels", vide: true },
      { chemin: "/marketing/espaces-publicitaires", titre: "Espaces publicitaires", vide: true },
      { chemin: "/marketing/programme-fidelite", titre: "Programme fidélité", vide: true },
      { chemin: "/marketing/programme-parrainage", titre: "Programme parrainage", vide: true },
      { chemin: "/marketing/publicites-pro", titre: "Publicités professionnelles", vide: true },
    ],
  },
  {
    prefixe: "/mobile",
    titre: "Applications mobiles",
    entrees: [
      { chemin: "/mobile/app-android", titre: "Application Android", vide: true },
      { chemin: "/mobile/app-i-o-s", titre: "Application iOS", vide: true },
      { chemin: "/mobile/mode-hors-ligne", titre: "Mode hors ligne", vide: true },
      { chemin: "/mobile/notifications-push", titre: "Notifications push", vide: true },
    ],
  },
  {
    prefixe: "/operations",
    titre: "Opérations",
    entrees: [
      { chemin: "/operations/ambassadeurs", titre: "Ambassadeurs", vide: true },
      { chemin: "/operations/centre-acquisition", titre: "Centre acquisition", vide: true },
      { chemin: "/operations/centre-audit", titre: "Centre audit", vide: true },
      { chemin: "/operations/centre-conformite", titre: "Centre conformité", vide: true },
      { chemin: "/operations/centre-donnees-marche", titre: "Centre données marché", vide: true },
      { chemin: "/operations/centre-expansion", titre: "Centre expansion", vide: true },
      { chemin: "/operations/centre-opportunites", titre: "Centre opportunités", vide: true },
      { chemin: "/operations/centre-previsions", titre: "Centre prévisions", vide: true },
      { chemin: "/operations/centre-risques", titre: "Centre risques", vide: true },
      { chemin: "/operations/centre-validation", titre: "Centre validation", vide: true },
      { chemin: "/operations/controle-qualite-global", titre: "Contrôle qualité global", vide: true },
      { chemin: "/operations/m-k-a-p-m-s-afrique", titre: "MKA.P-MS Afrique", vide: true },
      { chemin: "/operations/m-k-a-p-m-s-assurance", titre: "MKA.P-MS Assurance", vide: false },
      { chemin: "/operations/m-k-a-p-m-s-banque", titre: "MKA.P-MS Banque", vide: false },
      { chemin: "/operations/m-k-a-p-m-s-mobility", titre: "MKA.P-MS Mobility", vide: true },
      { chemin: "/operations/m-k-a-p-m-s-transport", titre: "MKA.P-MS Transport", vide: true },
      { chemin: "/operations/objectif-final-plateforme", titre: "Objectif final MKA.P-MS", vide: true },
      { chemin: "/operations/programme-entreprises-strategiques", titre: "Programme entreprises stratégiques", vide: true },
      { chemin: "/operations/programme-premium", titre: "Programme Premium", vide: true },
      { chemin: "/operations/tableau-bord-fondateur", titre: "Tableau de bord fondateur", vide: true },
    ],
  },
  {
    prefixe: "/pro",
    titre: "Espace professionnel",
    entrees: [
      { chemin: "/pro/avis", titre: "Avis reçus", vide: false },
      { chemin: "/pro/dossier", titre: "Dossier", vide: false },
      { chemin: "/pro/demarrer", titre: "Portail Professionnel MKA.P-MS", vide: false },
    ],
  },
  {
    prefixe: "/recrutement",
    titre: "Recrutement",
    entrees: [
      { chemin: "/recrutement/depot-c-v", titre: "Dépôt CV", vide: true },
      { chemin: "/recrutement/offres-emploi", titre: "Offres emploi", vide: true },
      { chemin: "/recrutement/recherche-talents", titre: "Recherche talents", vide: true },
    ],
  },
];

export const SECTIONS_ECRANS_TOTAL = 253;
export const SECTIONS_ECRANS_VIDES = 247;

/** Section correspondant à un préfixe (`/labs`), ou null. */
export function sectionParPrefixe(prefixe: string): SectionSommaire | null {
  return SECTIONS_SOMMAIRE.find((s) => s.prefixe === prefixe) ?? null;
}
